[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node index.js"
healthcheckPath = "/api/online"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
installCommand = "cd server && npm install"
